
eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ThisIsMyJwtSecretKey123456789ABCDEF

spring:
  kafka:
    listener:
      ack-mode: manual
      concurrency: 2
      observation-enabled: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: stream-service
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        specific.avro.reader: true
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:9091}




video:
  dir: ../videos/hls
